app:
  name: "your/module/path"
  env: "local"
  timezone: "Asia/Dhaka"

database:
  default: mysql
  connections:
    mysql:
      host: 127.0.0.1
      port: 3306
      database: your/module/path
      username: root
      password: 
    pgsql:
      host: 127.0.0.1
      port: 5432
      database: pgress
      username: pgress
      password: 123123
    sqlite:
      path: golara.db
    sqlserver:
      host: 127.0.0.1
      port: 1433
      database: golara
      username: sa
      password: secret
    mongodb:
      uri: mongodb://root:secret@127.0.0.1:27017/golara
server:
  host: 0.0.0.0
  port: 9092
  
redis:
  enabled: true
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
